### ISSUE TITLE
Add whileJust and untilJust

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-tailrec#26]
I have defined this helpers in different projects, and others have done the same too, for example `untilJust` is same as [loop](https://github.com/purescript-contrib/purescript-coroutines/blob/master/src/Control/Coroutine.purs#L53-L54), [filtered](https://github.com/purescript/purescript-gen/blob/v2.1.1/src/Control/Monad/Gen.purs#L113-L113),[untilSuccessful](https://github.com/juspay/purescript-presto/blob/v0.4.0/src/Presto/Core/Operators.purs#L24-L24). I would like to add this basic and useful helpers to this lib: 

```purs
-- | While supplied computation evaluates to `Just _`, it will be
-- | evaluated repeatedly and results will be combined using monoid instance.
whileJust :: forall a m. Monoid a => MonadRec m => m (Maybe a) -> m a
whileJust m = tailRecM (\v -> m <#> maybe (Done v) (Loop <<< (v <> _))) mempty

-- | Supplied computation will be executed repeatedly until it evaluates
-- | to `Just value` and then that `value` will be returned.
untilJust :: forall a m. MonadRec m => m (Maybe a) -> m a
untilJust m = tailRecM (\_ -> m <#> maybe (Loop unit) Done) unit

```

They are defined in here too http://hackage.haskell.org/package/monad-loops-0.4.3/docs/Control-Monad-Loops.html, There is also it's PS version of this lib, but looks like it's unmaintained https://github.com/mlang/purescript-monad-loops

---

One argument against adding this funcitons is that it will open can of warms and we would wanna add more and more later and it should instead be done in separate purescript-monad-loops like lib. 

I get that the that point, but I think adding `whileJust` and `untilJust` will be worthwhile as they are useful and sort of basic constructs.

to convince why I think {while,until}Just are basic functions see this implementations:
```purs
whileM :: forall a m. MonadRec m => Monoid a => m Boolean -> m a -> m a
whileM mCondition mRes = whileJust do
  condition <- mCondition
  if condition then mRes <#> Just else pure $ Nothing

untilM :: forall a m. Monoid a => MonadRec m => m a -> m Boolean -> m a
untilM mRes mCondition = whileJust do
  res <- mRes
  condition <- mCondition
  pure $ if condition then Nothing else Just res

iterateWhile :: forall a m. MonadRec m => (a -> Boolean) -> m a -> m a
iterateWhile p = iterateUntil $ not p

iterateUntil :: forall a m. MonadRec m => (a -> Boolean) -> m a -> m a
iterateUntil p x = x >>= iterateUntilM p (const x)

iterateUntilM :: forall a m. MonadRec m => (a -> Boolean) -> (a -> m a) -> a -> m a
iterateUntilM p f = execStateT $ whileM (gets p) (get >>= f >>> lift >>= put)
```

**Comment by hdgarrood** [comment]
These do seem like useful functions which should exist in core or at least contrib. Another option is bringing the monad-loops library into core or contrib, perhaps? I think it probably makes more sense to keep the non-MonadRec variants of the various looping functions together with the MonadRec ones.

I think it’s probably also worth putting together an explanation of when you want the MonadRec variant or not, as I think that might inform where we want to put them. I guess that for monads which can do stack safe monadic recursion by default (like Aff and Free), you want the non-MonadRec variants, and otherwise you want the MonadRec ones?

I also think using StateT to implement iterateUntilM is probably overkill; perhaps that would be better done using `tailRecM` directly.

**Comment by safareli** [comment]
Regarding non-MonadRec vs MonadRec version,

I think even with Free, FreeT or Aff it's fine to use this versions, they will just add small constant overhead, so I think it's better to use MonadRec versions all the time. Also this functions are mostly used with some blocking operations like `untillJust $ Bus.read <#> isReadyMsg` and in this cases small constant overhead is not an issue. but there might be some other need for non-MonadRec versions which i don't see.


> I also think using StateT to implement iterateUntilM is probably overkill; perhaps that would be better done using tailRecM directly.

Yes this implementations are just demonstrating usefulness of whileJust and untilJust.


---

Despite if purescript-monad-loops is moved/forked to contrib/core or if it also contains non-MonadRec version of funcitons, I think whileJust and untilJust can still be added to this lib next to `forever` as sort of core, recursive and "safe" operations, and  purescript-monad-loops can reexport them later. If you agree on this I can open PR adding whileJust and untilJust.

**Comment by hdgarrood** [comment]
Okay yeah, I think adding them here and then re-exporting them from monad-loops if we get around to moving that into core or contrib is sensible.

@natefaubion I'd be interested to hear your thoughts on this.

**Comment by natefaubion** [comment]
I think it makes sense to add them here.

**Comment by safareli** [comment]
here is the pr https://github.com/purescript/purescript-tailrec/pull/27
